# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551d0b1549aaf1f064a1dd687fc786b3a68cfaa75ae8884831c4582bd9a9965d68a8d2946e50b21ae2c8f161121085a0a3fc97d3e628b1b5b2f6fefb20206c68

test:
  secret_key_base: e5e5ce9c68adb81a54f01fbb2f4613aaaf726944067bb8d813362bfba7c82b6a055d403f2c87692675eb985ef1b2a3696de880368fb2d03f5427af591e7c1c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
